language: r
sudo: false
cache: packages
r:
  - "3.3.0"
  
install:
  - Rscript -e 'install.packages("ggplot2")'
  - Rscript -e 'install.packages("ggmap")'
  - Rscript -e 'install.packages("mapdata")'
  - Rscript -e 'install.packages("maps")'
  - Rscript -e 'install.packages("fields")'
  - Rscript -e 'install.packages("mapplots")'
  - Rscript -e 'install.packages("marmap")'
script:
  - Rscript -e 'devtools::check("ggplot2")'
  - Rscript -e 'devtools::check("ggmap")'
  - Rscript -e 'devtools::check("mapdata")'
  - Rscript -e 'devtools::check("maps")'
  - Rscript -e 'devtools::check("fields")'
  - Rscript -e 'devtools::check("mapplots")'
  - Rscript -e 'devtools::check("marmap")
script: 
 - ./MapProject.R
